import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "@/components/Provider";
import NotificationPannel from "@/components/ui/notification-pannel/NotificationPannel";
import UserContextProvider from "./contexts/userContext";
import { HomeIcon } from "@radix-ui/react-icons";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <UserContextProvider>
            <div className="flex justify-between absolute w-20 right-52 top-14 bg-white p-2 rounded-2xl shadow-md">
              <Link href="/">
                <HomeIcon />
              </Link>
              <NotificationPannel></NotificationPannel>
            </div>
            {children}
          </UserContextProvider>
        </Provider>
      </body>
    </html>
  );
}
